name: Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      APP_PATH: /home/${{ secrets.SSH_USER }}/zubrezh-bot
    steps:
      - uses: actions/checkout@v3
      - name: copy files
        uses: appleboy/scp-action@v0.1.4
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          source: 'package.json,yarn.lock,.env,ecosystem.config.js,src'
          target: ${{ env.APP_PATH }}
      - name: deploy bot
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          envs: APP_PATH
          script: |
            cd $APP_PATH
            yarn install
            npx pm2 startOrRestart ecosystem.config.js
